
---

plugins:
  - jest
  - testing-library

env:
  es2021: true
  browser: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'

parserOptions:
  ecmaVersion: 2021
  sourceType: module

settings:
  jest:
    version: 26
