---

plugins:
  - jest
  - testing-library
  - react

env:
  es2021: true
  browser: true
  jest: true

extends:
  - airbnb
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'

parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2021
  sourceType: module

settings:
  jest:
    version: 26
